### ISSUE TITLE
Can not compile the project

### ISSUE THREAD

**Issue by dadoonet** [seanstory/workplace-search-java#1] opened 2020-07-20 15:22 UTC
Hey

I tried to compile the project today:

```sh
$ mvn clean install
```

And got:

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] workplace-search-java                                              [pom]
[INFO] workplace-search-client                                            [jar]
[INFO] workplace-search-sdk                                               [jar]
[INFO] 
[INFO] ---------< com.sstory.workplace.search:workplace-search-java >----------
[INFO] Building workplace-search-java 7.8.0-SNAPSHOT                      [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ workplace-search-java ---
[INFO] 
[INFO] --- kotlin-maven-plugin:1.2.71:kapt (kapt) @ workplace-search-java ---
[WARNING] No sources found skipping Kotlin compile
[INFO] 
[INFO] --- kotlin-maven-plugin:1.2.71:compile (kotlin-compile) @ workplace-search-java ---
[WARNING] No sources found skipping Kotlin compile
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (java-compile) @ workplace-search-java ---
[INFO] No sources to compile
[INFO] 
[INFO] --- kotlin-maven-plugin:1.2.71:test-kapt (test-kapt) @ workplace-search-java ---
[WARNING] No sources found skipping Kotlin compile
[INFO] 
[INFO] --- kotlin-maven-plugin:1.2.71:test-compile (kotlin-test-compile) @ workplace-search-java ---
[WARNING] No sources found skipping Kotlin compile
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (java-groovy-testCompile) @ workplace-search-java ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ workplace-search-java ---
[INFO] Installing /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/pom.xml to /Users/dpilato/.m2/repository/com/sstory/workplace/search/workplace-search-java/7.8.0-SNAPSHOT/workplace-search-java-7.8.0-SNAPSHOT.pom
[INFO] 
[INFO] --------< com.sstory.workplace.search:workplace-search-client >---------
[INFO] Building workplace-search-client 7.8.0-SNAPSHOT                    [2/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ workplace-search-client ---
[INFO] Deleting /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/target
[INFO] 
[INFO] --- kotlin-maven-plugin:1.2.71:kapt (kapt) @ workplace-search-client ---
[WARNING] 'tools.jar' was not found, kapt may work unreliably
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jetbrains.kotlin.kapt3.base.javac.KaptJavaFileManager (file:/Users/dpilato/.m2/repository/org/jetbrains/kotlin/kotlin-annotation-processing-maven/1.2.71/kotlin-annotation-processing-maven-1.2.71.jar) to method com.sun.tools.javac.file.JavacFileManager.handleOption(com.sun.tools.javac.main.Option,java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.jetbrains.kotlin.kapt3.base.javac.KaptJavaFileManager
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ workplace-search-client ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/main/resources
[INFO] 
[INFO] --- kotlin-maven-plugin:1.2.71:compile (kotlin-compile) @ workplace-search-client ---
[WARNING] Duplicate source root: /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/target/generated-sources/kapt/compile
[WARNING] Duplicate source root: /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/target/generated-sources/kaptKotlin/compile
[WARNING] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/main/java/com/sstory/workplace/search/client/ContentSourceDocuments.kt: (11, 111) Unchecked cast: List<*> to Map<String, Any>
[WARNING] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/main/java/com/sstory/workplace/search/client/ContentSourceDocuments.kt: (15, 107) Unchecked cast: Map<*, *> to Map<String, Any>
[WARNING] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/main/java/com/sstory/workplace/search/client/Permissions.kt: (15, 137) Unchecked cast: Map<*, *> to Map<String, Any>
[WARNING] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/main/java/com/sstory/workplace/search/client/Permissions.kt: (19, 100) Unchecked cast: Map<*, *> to Map<String, Any>
[WARNING] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/main/java/com/sstory/workplace/search/client/Permissions.kt: (23, 98) Unchecked cast: Map<*, *> to Map<String, Any>
[WARNING] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/main/java/com/sstory/workplace/search/client/Permissions.kt: (27, 102) Unchecked cast: Map<*, *> to Map<String, Any>
[WARNING] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/main/java/com/sstory/workplace/search/client/Permissions.kt: (31, 105) Unchecked cast: Map<*, *> to Map<String, Any>
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (java-compile) @ workplace-search-client ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- kotlin-maven-plugin:1.2.71:test-kapt (test-kapt) @ workplace-search-client ---
[WARNING] No sources found skipping Kotlin compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ workplace-search-client ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/resources
[INFO] 
[INFO] --- kotlin-maven-plugin:1.2.71:test-compile (kotlin-test-compile) @ workplace-search-client ---
[WARNING] No sources found skipping Kotlin compile
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (java-groovy-testCompile) @ workplace-search-client ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
Ignoring GroovyBugError since it is likely caused by earlier issues.  Ignored problem is 'BUG! exception in phase 'semantic analysis' in source unit '/Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy' Attempt to change an immutable Groovy class: java.lang.Class'
Ignoring GroovyBugError since it is likely caused by earlier issues.  Ignored problem is 'BUG! exception in phase 'semantic analysis' in source unit '/Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy' Attempt to change an immutable Groovy class: java.lang.Class'
Ignoring GroovyBugError since it is likely caused by earlier issues.  Ignored problem is 'BUG! exception in phase 'semantic analysis' in source unit '/Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy' Attempt to change an immutable Groovy class: java.lang.Class'
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy:[1,1] 1. ERROR in /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy (at line 1)
	package com.sstory.workplace.search.client
	^
The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files

[ERROR] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy:[1,1] 2. ERROR in /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy (at line 1)
	package com.sstory.workplace.search.client
	^
The type java.lang.String cannot be resolved. It is indirectly referenced from required .class files

[ERROR] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy:[1,1] 3. ERROR in /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy (at line 1)
	package com.sstory.workplace.search.client
	^
The type java.lang.Class cannot be resolved. It is indirectly referenced from required .class files

[ERROR] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy:[1,1] 4. ERROR in /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy (at line 1)
	package com.sstory.workplace.search.client
	^
The type java.util.Map cannot be resolved. It is indirectly referenced from required .class files

[ERROR] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy:[1,1] 5. ERROR in /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy (at line 1)
	package com.sstory.workplace.search.client
	^
The type java.lang.Throwable cannot be resolved. It is indirectly referenced from required .class files

[ERROR] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy:[7,7] 6. ERROR in /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy (at line 7)
	class ClientTest extends Specification {
	      ^^^^^^^^^^
The hierarchy of the type ClientTest is inconsistent

[ERROR] Found 6 errors and 0 warnings.
[INFO] 7 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] workplace-search-java 7.8.0-SNAPSHOT ............... SUCCESS [  0.695 s]
[INFO] workplace-search-client ............................ FAILURE [  4.886 s]
[INFO] workplace-search-sdk 7.8.0-SNAPSHOT ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.667 s
[INFO] Finished at: 2020-07-20T17:21:18+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:testCompile (java-groovy-testCompile) on project workplace-search-client: Compilation failure: Compilation failure: 
[ERROR] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy:[1,1] 1. ERROR in /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy (at line 1)
[ERROR] 	package com.sstory.workplace.search.client
[ERROR] 	^
[ERROR] The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files
[ERROR] 
[ERROR] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy:[1,1] 2. ERROR in /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy (at line 1)
[ERROR] 	package com.sstory.workplace.search.client
[ERROR] 	^
[ERROR] The type java.lang.String cannot be resolved. It is indirectly referenced from required .class files
[ERROR] 
[ERROR] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy:[1,1] 3. ERROR in /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy (at line 1)
[ERROR] 	package com.sstory.workplace.search.client
[ERROR] 	^
[ERROR] The type java.lang.Class cannot be resolved. It is indirectly referenced from required .class files
[ERROR] 
[ERROR] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy:[1,1] 4. ERROR in /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy (at line 1)
[ERROR] 	package com.sstory.workplace.search.client
[ERROR] 	^
[ERROR] The type java.util.Map cannot be resolved. It is indirectly referenced from required .class files
[ERROR] 
[ERROR] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy:[1,1] 5. ERROR in /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy (at line 1)
[ERROR] 	package com.sstory.workplace.search.client
[ERROR] 	^
[ERROR] The type java.lang.Throwable cannot be resolved. It is indirectly referenced from required .class files
[ERROR] 
[ERROR] /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy:[7,7] 6. ERROR in /Users/dpilato/Documents/Elasticsearch/dev/workplace/workplace-search-java/workplace-search-client/src/test/java/com/sstory/workplace/search/client/ClientTest.groovy (at line 7)
[ERROR] 	class ClientTest extends Specification {
[ERROR] 	      ^^^^^^^^^^
[ERROR] The hierarchy of the type ClientTest is inconsistent
[ERROR] 
[ERROR] Found 6 errors and 0 warnings.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :workplace-search-client
```

Any idea?

**Comment by dadoonet** [comment] 2020-07-20 15:23
I'm using:

```sh
$ java -version
openjdk version "14" 2020-03-17
OpenJDK Runtime Environment (build 14+36-1461)
OpenJDK 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)
```

**Comment by dadoonet** [comment] 2020-07-20 18:04
Sounds like it works well from IntelliJ. :)

**Comment by seanstory** [comment] 2020-07-20 23:20
what's your maven version? `mvn clean install` is working for me. And travis CI is passing :/ 

```
Seans-MBP:workplace-search-java seanstory$ java -version
Picked up JAVA_TOOL_OPTIONS: -Dapple.awt.UIElement=true
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
Seans-MBP:workplace-search-java seanstory$ mvn --version
Picked up JAVA_TOOL_OPTIONS: -Dapple.awt.UIElement=true
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T10:06:16-05:00)
Maven home: /usr/local/Cellar/maven/3.6.2/libexec
Java version: 1.8.0_252, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
Seans-MBP:workplace-search-java seanstory$ 
```

Can I get you to try the `bugfix/1-get-java-build-working` branch? I've seen compiler issues resulting from this before.

If that doesn't do it, there must be a gap due to our different java versions (or maybe maven versions).

**Comment by seanstory** [comment] 2020-07-20 23:28
Nevermind, the java version is the issue, confirmed with Travis CI on an `openjdk14` JVM. I'll look into it 👀

**Comment by seanstory** [comment] 2020-07-21 01:13
@dadoonet I needed to update my groovy compiler version to work with newer JDKs. Can you checkout https://github.com/seanstory/workplace-search-java/tree/bugfix/1-get-java-build-working and validate? If it works for you, I'll merge that into master.

**Comment by sguerreropert** [comment] 2020-09-02 20:37
Hi, I have a similar problem:

java -version
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)

```
`Results :

Failed tests:   test yaml parsing(com.sstory.workplace.search.sdk.api.YamlConfigTest): Condition not satisfied:

Tests run: 3, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] workplace-search-java ............................. SUCCESS [1.540s]
[INFO] workplace-search-client ........................... SUCCESS [39.853s]
[INFO] workplace-search-sdk .............................. FAILURE [3.952s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 45.538s
[INFO] Finished at: Wed Sep 02 16:17:48 ART 2020
[INFO] Final Memory: 43M/375M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project workplace-search-sdk: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/prueba_rally/workplace-search-java/workplace-search-sdk/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :workplace-search-sdk
```
`

workplace-search-java/workplace-search-sdk/target/surefire-reports/com.sstory.workplace.search.sdk.api.YamlConfigTest.txt 


```
`-------------------------------------------------------------------------------
Test set: com.sstory.workplace.search.sdk.api.YamlConfigTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.004 sec <<< FAILURE!
test yaml parsing(com.sstory.workplace.search.sdk.api.YamlConfigTest)  Time elapsed: 0.447 sec  <<< FAILURE!
Condition not satisfied:

exceptionMsg.contains(expectedErrMsg)
|            |        |
|            false    No such file or directory
src/test/resources/four.yml (No existe el fichero o el directorio)

        at com.sstory.workplace.search.sdk.api.YamlConfigTest.test yaml parsing(YamlConfigTest.groovy:22)
`
```
```

ls workplace-search-sdk/src/test/resources/
five.yml  one.yml  three.txt  two.yml
```


Any idea? Thanks!

**Comment by seanstory** [comment] 2020-09-02 21:10
@sguerreropert your issue is unrelated, I've created a separate issue here: https://github.com/seanstory/workplace-search-java/issues/3

**Comment by seanstory** [comment] 2020-09-02 21:11
I've merged in the `bugfix/1-get-java-build-working`  branch to address the java 9+ compilation issues. We can re-open if there are others, but the travisci build seems to think that compilation works now on newer versions of java.

**Closed as completed by seanstory** 2020-09-02 21:11 UTC
